### ISSUE TITLE
ckb-std version compatible problem?

### ISSUE THREAD

**Issue by code-monad** [cryptape/ckb-script-templates#18]
在尝试迁移旧代码的时候，原始repo里有一个依赖使用了0.14.3的std，所以我尝试把template生成的模板里的ckb-std版本修改为了 0.14.3，编译的时候会遇到如下的错误； 同时，我也做了一个最简的可复现的repo。 不知道是否能有兼容性的处理方案？ 
https://github.com/code-monad/ckb-compatible-test

   Compiling ckb-std v0.14.3
The following warnings were emitted during compilation:

warning: ckb-std@0.14.3: clang: error: argument unused during compilation: '-nostartfiles' [-Werror,-Wunused-command-line-argument]

error: failed to run custom build command for `ckb-std v0.14.3`

Caused by:
  process didn't exit successfully: `/Users/code/workspace/ckb-std-compatible-test/target/release/build/ckb-std-a96260a753188ad2/build-script-build` (exit status: 1)
  --- stdout
  OUT_DIR = Some(/Users/code/workspace/ckb-std-compatible-test/target/riscv64imac-unknown-none-elf/release/build/ckb-std-48cb6261d798a03d/out)
  TARGET = Some(riscv64imac-unknown-none-elf)
  OPT_LEVEL = Some(3)
  HOST = Some(aarch64-apple-darwin)
  cargo:rerun-if-env-changed=CC_riscv64imac-unknown-none-elf
  CC_riscv64imac-unknown-none-elf = None
  cargo:rerun-if-env-changed=CC_riscv64imac_unknown_none_elf
  CC_riscv64imac_unknown_none_elf = None
  cargo:rerun-if-env-changed=TARGET_CC
  TARGET_CC = Some(clang)
  cargo:rerun-if-env-changed=CC_KNOWN_WRAPPER_CUSTOM
  CC_KNOWN_WRAPPER_CUSTOM = None
  RUSTC_WRAPPER = None
  cargo:rerun-if-env-changed=CC_ENABLE_DEBUG_OUTPUT
  cargo:rerun-if-env-changed=CRATE_CC_NO_DEFAULTS
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some(false)
  cargo:rerun-if-env-changed=CFLAGS_riscv64imac-unknown-none-elf
  CFLAGS_riscv64imac-unknown-none-elf = None
  cargo:rerun-if-env-changed=CFLAGS_riscv64imac_unknown_none_elf
  CFLAGS_riscv64imac_unknown_none_elf = None
  cargo:rerun-if-env-changed=TARGET_CFLAGS
  TARGET_CFLAGS = None
  cargo:rerun-if-env-changed=CFLAGS
  CFLAGS = None
  cargo:warning=clang: error: argument unused during compilation: '-nostartfiles' [-Werror,-Wunused-command-line-argument]

  --- stderr

  error occurred: Command "clang" "-O3" "-ffunction-sections" "-fdata-sections" "--target=riscv64-unknown-none-elf" "-static" "-I" "dl-c-impl/ckb-c-stdlib" "-I" "dl-c-impl/ckb-c-stdlib/libc" "-Wall" "-Wextra" "-O3" "-fno-builtin-printf" "-fno-builtin-memcmp" "-nostdinc" "-nostdlib" "-fvisibility=hidden" "-fdata-sections" "-ffunction-sections" "-Wall" "-Werror" "-Wno-unused-parameter" "-Wno-nonnull" "-nostartfiles" "-Wno-dangling-pointer" "-Wno-nonnull-compare" "-D__SHARED_LIBRARY__" "-o" "/Users/code/workspace/ckb-std-compatible-test/target/riscv64imac-unknown-none-elf/release/build/ckb-std-48cb6261d798a03d/out/6a56d8f237a70f55-lib.o" "-c" "dl-c-impl/lib.c" with args clang did not execute successfully (status code exit status: 1).

warning: build failed, waiting for other jobs to finish...
make[1]: *** [build] Error 101
make: *** [build] Error 2

**Comment by xxuejie** [comment]
The templates here were initially designed to be compatible with ckb-std 0.15.0, and as the templates get upgraded, newer version of ckb-std will be used.

We won't be able to provide support for older ckb-std versions. We rely on certain features to simplify the template for future usages.
